# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('urban-routing-example', ['urban-routing', 'wifi', 'mesh', 'applications'])
    obj.source = 'urban-routing-example.cc'

